---
apiVersion: v1
kind: Service
metadata:
  name: fnapp-ingress-gw-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 8088
      protocol: TCP
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    app: fnapp-ingress-gw

---
kind: Pod
apiVersion: v1
metadata:
  name: fnapp-ingress-gw
  labels:
    app: fnapp-ingress-gw
spec:
    containers:
      - name: envoy
        image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.27.2.0-prod 
        env:
        - name: APPMESH_RESOURCE_ARN
          value: arn:aws:appmesh:us-east-1:$ACCOUNT-ID:mesh/pod-service-mesh/virtualNode/in-gw_default
        - name: ENVOY_LOG_LEVEL
          value: "debug"
        ports:
          - containerPort: 8088
