---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: blue-green-app
spec:
  listeners:
    - portMapping:
       port: 8085
       protocol: http
  routes:
    - name: blue-green-app-route
      httpRoute:
        match:
          prefix: '/'
        action:
         weightedTargets:
            - virtualNodeRef:
                name: green-app-svc-node
              weight: 50
              port: 8080
            - virtualNodeRef:
                name: blue-app-svc-node
              weight: 50
              port: 8081
