---
kind: Pod
apiVersion: v1
metadata:
  name: fn-app
  labels:
    app: fn-app
spec:
  containers:
    - name: fnapp
      image: iconx2020a/eks:fnapp-green
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fn-app-pod-svc
spec:
  selector:
    app: fn-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
