---
kind: Pod
apiVersion: v1
metadata:
  name: fnapp-ingress-gw
  labels:
    app: fnapp-ingress-gw
spec:
  containers:
    - name: envoy
      image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.27.2.0-prod 
      env:
      - name: APPMESH_RESOURCE_ARN
        value: arn:aws:appmesh:us-east-1:${ACCOUNT-ID}:mesh/pod-service-mesh/virtualGateway/fnapp-ingress-gw_default
      - name: ENVOY_LOG_LEVEL
        value: "debug"
      ports:
        - containerPort: 8088