---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: fnapp-router
spec:
  listeners:
    - portMapping:
       port: 8085
       protocol: http
  routes:
    - name: fnapp-route
      httpRoute:
        match:
          prefix: '/'
        action:
         weightedTargets:
            - virtualNodeRef:
                name: fnapp-green
              weight: 50
              port: 8080
            - virtualNodeRef:
                name: fnapp-blue
              weight: 50
              port: 8080
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: blue-green-fnapp
spec:
  awsName: blue-green-fnapp.default.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: fnapp-router

---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-fnapp
  labels:
    app: blue-green-fnapp
spec:
  ports:
    - port: 8085
      name: http
  